name: Build

on: pull_request

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"
      - name: Install yarn dependencies
        run: yarn

      - name: Build dist
        run: yarn build
