name: Publish Site

on:
  push:
    tags:
      - "v*.*.*"

env:
  BUCKET_NAME: cupid-barman0-deafening-progress/asdfasdfwerqwerqxva
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"
      - name: Version
        run: echo VERSION=$(node -p "require('./package.json').version") >> $GITHUB_ENV

      - name: tag version
        run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Verify version of package.json and tag match
        if: ${{ !endsWith(env.TAG_VERSION, env.VERSION)}}
        run: exit 1

      - name: Install yarn dependencies
        run: yarn

      - name: Build dist
        env:
          GH_TOKEN: ${{secrets.VALK_TOKEN}}
        run: VALK_BASE_URL="/${{env.BUCKET_NAME}}/${{ env.VERSION }}/" yarn build

      - id: "auth"
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WIP }}
          service_account: ${{ secrets.GCP_SA }}
          access_token_lifetime: "60s"

      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      # Check if version folder exist.
      - id: check-exist
        name: Check if exist
        continue-on-error: true
        run: gsutil -q stat "gs://${{ env.BUCKET_NAME }}/${{ env.VERSION }}"

      - name: Remove if version exist
        if: steps.check-exist.outcome == 'success'
        run: gsutil rm -r "gs://${{ env.BUCKET_NAME }}/${{ env.VERSION }}"

      - id: "upload-files"
        name: upload new version
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "build"
          destination: "${{env.BUCKET-NAME}}/${{ env.version}}"
          parent: false
